image: ubuntu:24.04

before_script:
  - chmod +x setup-wio.sh
  - ./setup-wio.sh

stages:
  - build

compile:
  stage: build
  tags:
    - docker
  script:
    - export PATH=$PATH:/root/bin             # set the path to arduino-cli installation folder
    - pwd                                     # print the current working directory
    - cd wio                          				# change the directory to arduino folder
    - echo "$SECRETS" > secrets.h           # import secrets from GitLAB CI/CD Settings -> Variables
    - cat secrets.h
    - arduino-cli lib list                    # check that libraries are installed
    
    # Compile
    - arduino-cli compile --fqbn Seeeduino:samd:seeed_wio_terminal

  except:
    - tags