spring.application.name=silo-web-app
# enable SQL logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
spring.datasource.url=jdbc:postgresql://ep-royal-wave-a2b8a253.eu-central-1.aws.neon.tech/graindb?user=graindb_owner&password=NnHq21kchyWT&sslmode=require
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect